name: Build and Publish Package

on:
  push:
    branches: ["main", "develop"]
    paths:
      # Só executa quando a versão for alterada neste arquivo
      - "ValidaDiaUtilBR/ValidaDiaUtilBR.csproj" # altere a tag <Version> para publicar
  pull_request:
    branches: ["main", "develop"]

jobs:
  validate:
    name: Validate Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build (Debug)
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal

  publish:
    name: Build and Publish Package
    runs-on: ubuntu-latest
    needs: validate
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build (Release)
        run: dotnet build ./ValidaDiaUtilBR/ValidaDiaUtilBR.csproj -c Release --no-restore
      - name: Generate Package
        run: dotnet pack ./ValidaDiaUtilBR/ValidaDiaUtilBR.csproj -c Release -o ./dist/
      - name: Publish Package
        run: dotnet nuget push ./dist/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
